//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleAnswer
    {
        public long Id { get; set; }
        public string text { get; set; }
        public long Question_Id { get; set; }
        public Nullable<int> Answer_number { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
