//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.PossibleAnswers = new HashSet<PossibleAnswer>();
            this.CorrectAnswers = new HashSet<CorrectAnswer>();
            this.Statistics = new HashSet<Statistic>();
        }
    
        public long Id { get; set; }
        public string Question_text { get; set; }
        public Nullable<int> Question_number { get; set; }
        public long Quiz_Id { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleAnswer> PossibleAnswers { get; set; }
        public virtual Quiz Quizze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrectAnswer> CorrectAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistic> Statistics { get; set; }
    }
}
