//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public long Id { get; set; }
        public long Team_Id { get; set; }
        public long User_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Team Team { get; set; }
    }
}
